// tacoclicker-rs/src/tests/std/mod.rs
// This file will be automatically generated by build.rs
// It contains the compiled WASM binaries for testing
// Based on patterns from ./reference/alkanes-rs/src/tests/std/mod.rs

// Placeholder - will be populated by build script
// The build script will generate modules like:
// pub mod alkanes_std_tacoclicker_build;
// pub mod free_mint_build;
// etc.

// For now, we'll include a basic placeholder to prevent compilation errors
pub mod alkanes_std_tacoclicker_build {
    use hex_lit::hex;
    #[allow(long_running_const_eval)]
    pub fn get_bytes() -> Vec<u8> {
        // Placeholder - will be replaced by actual WASM binary from build script
        vec![]
    }
}

pub mod free_mint_build {
    use hex_lit::hex;
    #[allow(long_running_const_eval)]
    pub fn get_bytes() -> Vec<u8> {
        // Placeholder - will be replaced by actual WASM binary from build script
        vec![]
    }
}